spring:
  application:
    name: spring-oauth2-security-example
security:
  oauth2:
    client:
      clientId: 295636171573188
      clientSecret: 1a6f607b81d0c1f788d5d46e05da4f75
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me